const TIMER_CREATE = 'TIMER_CREATE';
const TIMER_DELETE = 'TIMER_DELETE';
const TIMER_COMPLETE = 'TIMER_COMPLETE';
const SUPER_TIMER_START = 'SUPER_TIMER_START';
const SUPER_TIMER_TICK = 'SUPER_TIMER_TICK';
const SUPER_TIMER_COMPLETE = 'SUPER_TIMER_COMPLETE';

export {
  TIMER_CREATE,
  TIMER_COMPLETE,
  TIMER_DELETE,
  SUPER_TIMER_START,
  SUPER_TIMER_TICK,
  SUPER_TIMER_COMPLETE,
};
