const TIMER_CREATE = 'TIMER_CREATE';
const TIMER_DELETE = 'TIMER_DELETE';
const TIMER_COMPLETE = 'TIMER_COMPLETE';

const SUB_TIMER_CREATE = 'SUB_TIMER_CREATE';

const SUPER_TIMER_START = 'SUPER_TIMER_START';
const SUPER_TIMER_TICK = 'SUPER_TIMER_TICK';
const SUPER_TIMER_COMPLETE = 'SUPER_TIMER_COMPLETE';

const END_TIME_SET = 'END_TIME_SET';

export {
  TIMER_CREATE,
  SUB_TIMER_CREATE,
  TIMER_COMPLETE,
  TIMER_DELETE,
  SUPER_TIMER_START,
  SUPER_TIMER_TICK,
  SUPER_TIMER_COMPLETE,
  END_TIME_SET,
};
