const TIMER_CREATED = 'TIMER_CREATED';
const TIMER_DELETED = 'TIMER_DELETED';
const TIMER_COMPLETED = 'TIMER_COMPLETED';

const SUB_TIMER_CREATED = 'SUB_TIMER_CREATED';

const SUPER_TIMER_STARTED = 'SUPER_TIMER_STARTED';
const SUPER_TIMER_TICKED = 'SUPER_TIMER_TICKED';
const SUPER_TIMER_COMPLETED = 'SUPER_TIMER_COMPLETED';

const END_TIME_SET = 'END_TIME_SET';

export {
  TIMER_CREATED,
  SUB_TIMER_CREATED,
  TIMER_COMPLETED,
  TIMER_DELETED,
  SUPER_TIMER_STARTED,
  SUPER_TIMER_TICKED,
  SUPER_TIMER_COMPLETED,
  END_TIME_SET,
};
